s3_uri: "s3://2023-get-xf2217/get_demo"
share: false
port: 7860
host: "127.0.0.1"
s3_file_sys: NULL
celltype:
  features: "NrMotifV1"
  num_region_per_sample: 200
  data_dir: "/home/xf2217/Projects/pretrain_human_bingren_shendure_apr2023/k562/"
  interpret_dir: "/home/xf2217/Projects/geneformer_nova/interpret_input_masked/"
  input: True
  jacob: True
  embed: True
  assets_dir: '.'
  motif_dir: '.'
  num_cls: 2
